
FROM node:16-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build


FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY ecosystem.config.js ./

RUN npm ci --only=production
RUN npm install -g pm2

ENV PORT=4000
EXPOSE 4000

CMD ["pm2-runtime", "ecosystem.config.js"]
